package com.tvm.privateclient

import java.security.MessageDigest
import java.security.SecureRandom
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone
import java.util.UUID
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import org.json.JSONArray
import org.json.JSONObject

/**
 * Accounts on the phone.
 *
 * The Android build runs its own embedded core, so the gate the interface puts
 * in front of everything has to be answered here rather than by a desktop
 * somewhere. Without this the app loads, asks who is signed in, gets nothing,
 * and sits on a sign-in form that cannot register anybody.
 *
 * The rules match the TypeScript core exactly: an account starts inert,
 * activation is the only route to using TVM, a wrong password and a missing
 * account give the same answer, and nothing stored can produce a password.
 * PBKDF2-HMAC-SHA256 rather than the desktop's scrypt, for the same reason as
 * the developer code — scrypt is not in the Android platform libraries.
 *
 * Accounts live in the app-private container, which Android isolates per app.
 * The owner activates one by unlocking developer mode with the universal code.
 */
object TvmPassword {
    private const val ITERATIONS = 210_000
    private val random = SecureRandom()

    fun newSalt(): String {
        val bytes = ByteArray(16)
        random.nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }

    fun hash(password: String, salt: String): String? = try {
        val spec = PBEKeySpec(password.toCharArray(), salt.hexToBytes(), ITERATIONS, 256)
        val derived = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).encoded
        spec.clearPassword()
        derived.joinToString("") { "%02x".format(it) }
    } catch (error: Exception) {
        null
    }

    /** No early exit: how long a check takes must not say how much was right. */
    fun matches(password: String, expected: String, salt: String): Boolean {
        val actual = hash(password, salt) ?: return false
        if (actual.length != expected.length) return false
        var difference = 0
        for (index in actual.indices) difference = difference or (actual[index].code xor expected[index].code)
        return difference == 0
    }

    private fun String.hexToBytes(): ByteArray =
        ByteArray(length / 2) { substring(it * 2, it * 2 + 2).toInt(16).toByte() }
}

/**
 * `readAccess` hands back the bundled Access.json. Passed in as a lambda the
 * way the catalogue already is, so this class needs no Android framework type and
 * stays testable off-device.
 */
class TvmAccounts(private val store: TvmStore, private val readAccess: () -> String?) {
    private val file = "accounts.json"
    private val sessionMillis = 30L * 86_400_000L
    private val random = SecureRandom()

    // ---- Access resource (generated by scripts/export-access.mjs) ----------

    private var cachedAccess: JSONObject? = null

    fun access(): JSONObject {
        cachedAccess?.let { return it }
        val text = runCatching { readAccess() }.getOrNull() ?: return JSONObject()
        val parsed = runCatching { JSONObject(text) }.getOrNull() ?: JSONObject()
        cachedAccess = parsed
        return parsed
    }

    fun termsVersion(): String = access().text("termsVersion", "")

    // ---- Storage ----------------------------------------------------------

    private fun load(): Pair<MutableList<JSONObject>, JSONObject> {
        val root = store.readJSON(file) as? JSONObject ?: JSONObject()
        val rows = root.optJSONArray("accounts") ?: JSONArray()
        val accounts = MutableList(rows.length()) { rows.getJSONObject(it) }
        val sessions = root.optJSONObject("sessions") ?: JSONObject()
        // Expired sessions are dropped whenever the ledger is touched.
        val now = System.currentTimeMillis()
        val live = JSONObject()
        for (key in sessions.keys()) {
            val session = sessions.optJSONObject(key) ?: continue
            if (parseIso(session.text("expiresAt")) > now) live.put(key, session)
        }
        return accounts to live
    }

    private fun save(accounts: List<JSONObject>, sessions: JSONObject) {
        store.writeJSON(file, JSONObject().apply {
            put("version", 1)
            put("accounts", JSONArray(accounts))
            put("sessions", sessions)
        })
    }

    private fun iso(at: Date = Date()): String {
        val format = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US)
        format.timeZone = TimeZone.getTimeZone("UTC")
        return format.format(at)
    }

    private fun parseIso(value: String): Long = runCatching {
        val format = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US)
        format.timeZone = TimeZone.getTimeZone("UTC")
        format.parse(value)?.time ?: 0L
    }.getOrDefault(0L)

    private fun digest(token: String): String =
        MessageDigest.getInstance("SHA-256").digest(token.toByteArray()).joinToString("") { "%02x".format(it) }

    private fun newToken(): String {
        val bytes = ByteArray(32)
        random.nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }

    private fun normalize(email: String) = email.trim().lowercase(Locale.US)

    private fun emailLooksValid(email: String): Boolean {
        if (email.length > 254 || email.contains(' ')) return false
        val parts = email.split("@")
        if (parts.size != 2 || parts[0].isEmpty()) return false
        val host = parts[1]
        val dot = host.lastIndexOf('.')
        return dot > 0 && host.length - dot > 2
    }

    // ---- Rules ------------------------------------------------------------

    /** Identical to the desktop core: activation, a tier, current terms, not suspended. */
    fun usable(account: JSONObject?): JSONObject {
        val out = JSONObject()
        if (account == null) return out.put("ok", false).put("reason", "no_account")
        if (account.optBoolean("suspended")) return out.put("ok", false).put("reason", "suspended")
        if (!account.optBoolean("activated") || account.text("tier").isEmpty()) {
            return out.put("ok", false).put("reason", "awaiting_activation")
        }
        if (account.text("termsVersion") != termsVersion() || account.text("termsAcceptedAt").isEmpty()) {
            return out.put("ok", false).put("reason", "terms_required")
        }
        return out.put("ok", true).put("reason", JSONObject.NULL)
    }

    /** Never includes the digest or the salt. */
    fun publicOf(account: JSONObject): JSONObject = publicJson(account)

    private fun publicJson(account: JSONObject): JSONObject = JSONObject().apply {
        put("id", account.text("id"))
        put("email", account.text("email"))
        put("displayName", account.text("displayName"))
        put("activated", account.optBoolean("activated"))
        put("tier", account.opt("tier") ?: JSONObject.NULL)
        put("suspended", account.optBoolean("suspended"))
        put("createdAt", account.text("createdAt"))
        put("termsVersion", account.opt("termsVersion") ?: JSONObject.NULL)
        put("termsAcceptedAt", account.opt("termsAcceptedAt") ?: JSONObject.NULL)
    }

    private fun adminJson(account: JSONObject, activeSessions: Int): JSONObject =
        publicJson(account).apply {
            put("activatedAt", account.opt("activatedAt") ?: JSONObject.NULL)
            put("lastSeenAt", account.opt("lastSeenAt") ?: JSONObject.NULL)
            put("signIns", account.optInt("signIns"))
            put("lastClient", account.opt("lastClient") ?: JSONObject.NULL)
            put("note", account.opt("note") ?: JSONObject.NULL)
            put("activeSessions", activeSessions)
        }

    // ---- Actions ----------------------------------------------------------

    fun register(rawEmail: String, password: String, displayName: String?, client: String?): Result<JSONObject> {
        val email = normalize(rawEmail)
        if (!emailLooksValid(email)) return Result.failure(Exception("Enter a valid email address."))
        if (password.length < 10) return Result.failure(Exception("Use at least 10 characters."))
        if (password.length > 200) return Result.failure(Exception("That password is too long."))

        val (accounts, sessions) = load()
        // Saying "already registered" would turn signup into a way of testing
        // which addresses have accounts.
        if (accounts.any { it.text("email") == email }) {
            return Result.failure(Exception("That account could not be created. If it already exists, sign in instead."))
        }

        val salt = TvmPassword.newSalt()
        val hash = TvmPassword.hash(password, salt)
            ?: return Result.failure(Exception("That account could not be created."))
        val account = JSONObject().apply {
            put("id", "acc_" + UUID.randomUUID().toString().replace("-", ""))
            put("email", email)
            put("displayName", (displayName?.trim()?.ifEmpty { null } ?: email.substringBefore('@')).take(80))
            put("passwordHash", hash)
            put("passwordSalt", salt)
            put("createdAt", iso())
            put("activated", false)
            put("activatedAt", JSONObject.NULL)
            put("tier", JSONObject.NULL)
            put("note", JSONObject.NULL)
            put("suspended", false)
            put("termsVersion", JSONObject.NULL)
            put("termsAcceptedAt", JSONObject.NULL)
            put("lastSeenAt", JSONObject.NULL)
            put("signIns", 0)
            put("lastClient", client?.take(200) ?: JSONObject.NULL)
        }
        accounts.add(account)
        save(accounts, sessions)
        return Result.success(publicJson(account))
    }

    fun signIn(rawEmail: String, password: String, client: String?): Result<JSONObject> {
        val email = normalize(rawEmail)
        val (accounts, sessions) = load()
        val index = accounts.indexOfFirst { it.text("email") == email }
        if (index < 0) {
            // Do the work anyway so a missing account and a wrong password take
            // the same time and cannot be told apart from outside.
            TvmPassword.hash(password, TvmPassword.newSalt())
            return Result.failure(Exception("That email address and password do not match."))
        }
        val account = accounts[index]
        val ok = TvmPassword.matches(password, account.text("passwordHash"), account.text("passwordSalt"))
        if (!ok) return Result.failure(Exception("That email address and password do not match."))

        val token = newToken()
        val now = Date()
        account.put("lastSeenAt", iso(now))
        account.put("signIns", account.optInt("signIns") + 1)
        if (client != null) account.put("lastClient", client.take(200))
        sessions.put(digest(token), JSONObject().apply {
            put("accountId", account.text("id"))
            put("issuedAt", iso(now))
            put("expiresAt", iso(Date(now.time + sessionMillis)))
            put("client", client ?: JSONObject.NULL)
        })
        save(accounts, sessions)
        return Result.success(JSONObject().apply {
            put("token", token)
            put("account", publicJson(account))
            put("usable", usable(account))
        })
    }

    fun signOut(token: String) {
        val (accounts, sessions) = load()
        sessions.remove(digest(token))
        save(accounts, sessions)
    }

    fun resolve(token: String?): JSONObject? {
        if (token.isNullOrEmpty()) return null
        val (accounts, sessions) = load()
        val session = sessions.optJSONObject(digest(token)) ?: return null
        val id = session.text("accountId")
        return accounts.firstOrNull { it.text("id") == id }
    }

    fun acceptTerms(id: String): JSONObject? {
        val (accounts, sessions) = load()
        val account = accounts.firstOrNull { it.text("id") == id } ?: return null
        account.put("termsVersion", termsVersion())
        account.put("termsAcceptedAt", iso())
        save(accounts, sessions)
        return publicJson(account)
    }

    // ---- Owner ------------------------------------------------------------

    fun list(search: String?, state: String?): JSONObject {
        val (accounts, sessions) = load()
        val counts = mutableMapOf<String, Int>()
        for (key in sessions.keys()) {
            val id = sessions.optJSONObject(key)?.text("accountId") ?: continue
            counts[id] = (counts[id] ?: 0) + 1
        }
        val needle = (search ?: "").trim().lowercase(Locale.US)
        val filtered = accounts.filter { account ->
            if (needle.isNotEmpty()
                && !account.text("email").contains(needle)
                && !account.text("displayName").lowercase(Locale.US).contains(needle)
            ) return@filter false
            when (state) {
                "waiting" -> !account.optBoolean("activated") && !account.optBoolean("suspended")
                "active" -> account.optBoolean("activated") && !account.optBoolean("suspended")
                "suspended" -> account.optBoolean("suspended")
                else -> true
            }
        }.sortedByDescending { it.text("createdAt") }

        val tiers = JSONArray()
        val source = access().optJSONArray("tiers") ?: JSONArray()
        for (i in 0 until source.length()) {
            val tier = source.optJSONObject(i) ?: continue
            tiers.put(JSONObject().put("id", tier.text("id")).put("name", tier.text("name")))
        }

        return JSONObject().apply {
            put("accounts", JSONArray(filtered.map { adminJson(it, counts[it.text("id")] ?: 0) }))
            put("summary", JSONObject().apply {
                put("total", accounts.size)
                put("waiting", accounts.count { !it.optBoolean("activated") && !it.optBoolean("suspended") })
                put("active", accounts.count { it.optBoolean("activated") && !it.optBoolean("suspended") })
                put("suspended", accounts.count { it.optBoolean("suspended") })
            })
            put("tiers", tiers)
        }
    }

    fun activate(id: String, tier: String, note: String?): JSONObject? {
        if (tier != "stream" && tier != "stream-live") return null
        val (accounts, sessions) = load()
        val account = accounts.firstOrNull { it.text("id") == id } ?: return null
        account.put("activated", true)
        if (account.text("activatedAt").isEmpty()) account.put("activatedAt", iso())
        account.put("tier", tier)
        account.put("suspended", false)
        if (note != null) account.put("note", note.take(500))
        save(accounts, sessions)
        return adminJson(account, 0)
    }

    fun setSuspended(id: String, suspended: Boolean): JSONObject? {
        val (accounts, sessions) = load()
        val account = accounts.firstOrNull { it.text("id") == id } ?: return null
        account.put("suspended", suspended)
        if (suspended) {
            account.put("activated", false)
            // Revoking must not wait for a token to lapse.
            for (key in sessions.keys().asSequence().toList()) {
                if (sessions.optJSONObject(key)?.text("accountId") == id) sessions.remove(key)
            }
        }
        save(accounts, sessions)
        return adminJson(account, 0)
    }

    fun setNote(id: String, note: String?): JSONObject? {
        val (accounts, sessions) = load()
        val account = accounts.firstOrNull { it.text("id") == id } ?: return null
        account.put("note", note?.take(500) ?: JSONObject.NULL)
        save(accounts, sessions)
        return adminJson(account, 0)
    }

    fun erase(id: String) {
        val (accounts, sessions) = load()
        accounts.removeAll { it.text("id") == id }
        for (key in sessions.keys().asSequence().toList()) {
            if (sessions.optJSONObject(key)?.text("accountId") == id) sessions.remove(key)
        }
        save(accounts, sessions)
    }
}
