import { test, expect } from '@playwright/test';
import { FALLBACK_PLAN } from '../src/data/plan';
const film = {id:'tt1',title:'Finished film',year:2025,kind:'movie',poster:'',backdrop:'',genres:['Drama'],rating:'8',synopsis:'An original story.',playable:true,hue:220};
test('Anime purchase, scenes, notebook, bundle and quiet tableau', async ({page}) => {
  test.setTimeout(60000);
  let plan = {...FALLBACK_PLAN, catalog:[{id:'free',name:'Free',basePricePence:0,pricePence:0,price:'Free',mocks:false,liveTv:false,extras:[]}]};
  const packs: string[] = [];
  await page.addInitScript(()=>{localStorage.setItem('tvm.theme.isle-boot','1');localStorage.setItem('tvm.prefs',JSON.stringify({autoUpdate:false,language:'en'}));});
  await page.route('**/api/plan', route=>route.fulfill({json:plan}));
  await page.route('**/api/billing/checkout',async route=>{
    const body=route.request().postDataJSON();packs.push(body.pack);
    if(body.pack==='anime')plan={...plan,anime:true,animeOwned:true};
    if(body.pack==='theme-bundle')plan={...plan,bundle:true,bundleOwned:true,anime:true,animeOwned:true,synthwave:true,synthwaveOwned:true};
    await route.fulfill({json:plan});
  });
  await page.route('**/api/home',route=>route.fulfill({json:{rd:{configured:true,premium:true},featured:film,library:[film],watchlist:[film],continueWatching:[],finished:[film],adaptationGeneration:1,rails:[{id:'anime-adapted',title:'Adapted for you',items:[{...film,id:'tt2',title:'Next film'}]},{id:'films',title:'Films',items:[film,{...film,id:'tt3',title:'Brother film'}]}]}}));
  await page.route('**/api/profiles',route=>route.fulfill({json:{activeId:'p1',profiles:[{id:'p1',name:'Viewer',hue:22}]}}));
  await page.route('**/api/apps',route=>route.fulfill({json:{ribbon:[],grid:[]}}));
  await page.route('**/api/prefs',route=>route.fulfill({json:{language:'en',autoUpdate:false}}));
  await page.route('**/api/update/**',route=>route.fulfill({json:{kind:'up_to_date',notice:null,configured:false,available:null}}));
  await page.goto('/?e2e=1');
  await page.locator('.ribbon-zone').hover({ force: true });
  await page.locator('[data-focus-id="settings"]').click();
  await page.locator('[data-focus-id="theme-anime"]').click();
  await expect(page.getByRole('heading',{name:'Unlock Anime'})).toBeVisible();
  await page.locator('[data-focus-id="checkout-consent"]').click();
  await page.locator('[data-focus-id="pay"]').click();
  await expect(page.getByRole('heading',{name:'Your test plan is ready'})).toBeVisible();
  expect(packs).toEqual(['anime']);
  await page.locator('[data-focus-id="checkout-home"]').click();
  await expect(page.locator('.anime-stage')).toBeVisible();
  await expect(page.locator('.tvm-scene')).toHaveCount(0);
  await page.screenshot({path:'test-results/anime-six-eyes.png',animations:'disabled'});
  await page.locator('.ribbon-zone').hover({ force: true });
  await page.locator('[data-focus-id="settings"]').click();
  const sceneButtons = page.locator('.anime-scene-picker button');
  await expect(sceneButtons).toHaveCount(17);
  for (const button of await sceneButtons.all()) {
    const id = (await button.getAttribute('data-focus-id'))!.replace('anime-scene-', '');
    await button.click();
    await expect(page.locator('html')).toHaveAttribute('data-anime-scene', id);
    await expect(page.locator('.anime-tableau > g')).not.toHaveCount(0);
  }
  await page.locator('[data-focus-id="anime-scene-death-note"]').click();
  await page.keyboard.press('Escape');
  await expect(page.locator('.anime-notebook')).toContainText('Finished film');
  await page.screenshot({path:'test-results/anime-notebook.png',animations:'disabled'});
  await page.locator('.ribbon-zone').hover({ force: true });
  await page.locator('[data-focus-id="settings"]').click();
  await page.locator('[data-focus-id="anime-scene-mahoraga"]').click();
  await page.keyboard.press('Escape');
  await expect(page.getByText('TVM Stream · Adapted for you',{exact:true})).toBeVisible();
  await page.locator('.ribbon-zone').hover({ force: true });
  await page.locator('[data-focus-id="settings"]').click();
  await page.locator('[data-focus-id="performance"]').click();
  await expect(page.locator('.anime-stage')).toHaveAttribute('data-quiet','true');
  await page.locator('[data-focus-id="theme-bundle"]').click();
  await expect(page.getByRole('heading',{name:'Unlock All paid themes'})).toBeVisible();
  await page.locator('[data-focus-id="checkout-consent"]').click();
  await page.locator('[data-focus-id="pay"]').click();
  await expect(page.getByRole('heading',{name:'Your test plan is ready'})).toBeVisible();
  expect(packs).toEqual(['anime','theme-bundle']);
});

test('Six Eyes follows D-pad focus on a phone shell and freezes in reduced motion', async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await page.addInitScript(()=>{
    localStorage.setItem('tvm.theme.isle-boot','1');localStorage.setItem('tvm.theme','anime');
    localStorage.setItem('tvm.theme.anime.scene','gojo-six-eyes');
    document.addEventListener('DOMContentLoaded',()=>document.documentElement.classList.add('phone-shell'));
  });
  await page.route('**/api/plan',route=>route.fulfill({json:{...FALLBACK_PLAN,id:'basic',anime:true,animeOwned:true}}));
  await page.route('**/api/home',route=>route.fulfill({json:{rd:{configured:true,premium:true},featured:film,library:[],watchlist:[],continueWatching:[],rails:[]}}));
  await page.route('**/api/profiles',route=>route.fulfill({json:{activeId:'p1',profiles:[{id:'p1',name:'Viewer',hue:22}]}}));
  await page.route('**/api/apps',route=>route.fulfill({json:{ribbon:[],grid:[]}}));
  await page.route('**/api/prefs',route=>route.fulfill({json:{language:'en',autoUpdate:false}}));
  await page.goto('/?e2e=1');
  await expect(page.locator('.anime-stage')).toHaveAttribute('data-platform','mobile');
  const pupil = page.locator('.anime-eye > g > g').first();
  const before = await pupil.getAttribute('transform');
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('ArrowRight');
  await expect.poll(()=>pupil.getAttribute('transform')).not.toBe(before);
  await page.emulateMedia({reducedMotion:'reduce'});
  await expect(page.locator('.anime-stage')).toHaveAttribute('data-quiet','true');
  const still = await pupil.getAttribute('transform');
  await page.keyboard.press('ArrowLeft');
  await expect(pupil).toHaveAttribute('transform',still!);
  await page.screenshot({path:'test-results/anime-phone.png',animations:'disabled'});
});
